; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Librerías necesarias
lib_deps =
    ESP Async WebServer @ ^1.2.3
    AsyncTCP @ ^1.1.1
    ArduinoJson @ ^6.19.4
    WiFi @ ^2.0.0

monitor_speed = 115200

; Configuración para simulación en Wokwi
build_flags = 
    -DWOKWI_SIMULATION    ; Indica que estamos en modo simulación
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue