[wokwi]
version = 1
firmware = ".pio/build/esp32dev/firmware.bin"
elf = ".pio/build/esp32dev/firmware.elf"

# Reenvía el puerto 80 del ESP32 simulado al puerto 8180 de tu PC
[[net.forward]]
from = "localhost:8180"
to = "target:80"